// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_A14kmN9FZettTGkra4qfUSP8lTEGD78',
    appId: '1:8269170177:web:09e9938edf780bd9b32200',
    messagingSenderId: '8269170177',
    projectId: 'agronursery-734a8',
    authDomain: 'agronursery-734a8.firebaseapp.com',
    storageBucket: 'agronursery-734a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3f-ZEfuFzYu9zRE1Cen6jZ1GGzV1daGs',
    appId: '1:8269170177:android:6f56c4642d26ade7b32200',
    messagingSenderId: '8269170177',
    projectId: 'agronursery-734a8',
    storageBucket: 'agronursery-734a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzir9x70nwAVFRSKEDyvpMk_Pj3DCvQvo',
    appId: '1:8269170177:ios:e118e33e9c2dd521b32200',
    messagingSenderId: '8269170177',
    projectId: 'agronursery-734a8',
    storageBucket: 'agronursery-734a8.firebasestorage.app',
    iosBundleId: 'com.example.agroNursery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzir9x70nwAVFRSKEDyvpMk_Pj3DCvQvo',
    appId: '1:8269170177:ios:e118e33e9c2dd521b32200',
    messagingSenderId: '8269170177',
    projectId: 'agronursery-734a8',
    storageBucket: 'agronursery-734a8.firebasestorage.app',
    iosBundleId: 'com.example.agroNursery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_A14kmN9FZettTGkra4qfUSP8lTEGD78',
    appId: '1:8269170177:web:732a87efc2fc0ae7b32200',
    messagingSenderId: '8269170177',
    projectId: 'agronursery-734a8',
    authDomain: 'agronursery-734a8.firebaseapp.com',
    storageBucket: 'agronursery-734a8.firebasestorage.app',
  );
}
