import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

import 'package:easy_localization/easy_localization.dart';
import 'screens/role_selection.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Init localization (loads en/mr JSONs)
  await EasyLocalization.ensureInitialized();

  // Init Firebase for Android/Web/iOS using generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(
    EasyLocalization(
      supportedLocales: const [Locale('en'), Locale('mr')],
      path: 'assets/i18n', // e.g., assets/i18n/en.json, assets/i18n/mr.json
      fallbackLocale: const Locale('en'),
      child: const AgroNurseryApp(),
    ),
  );
}

class AgroNurseryApp extends StatelessWidget {
  const AgroNurseryApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'AgroNursery',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.green,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // hook up localization to the whole app
      localizationsDelegates: context.localizationDelegates,
      supportedLocales: context.supportedLocales,
      locale: context.locale,

      home: const RoleSelectionPage(), // Start from Role Selection
    );
  }
}
